export const posts = [
  {
    slug: 'nextjs-tailwind-setup',
    title: 'Setting Up Next.js with Tailwind CSS',
    excerpt: 'A beginner\'s guide to building fast websites.',
    date: '2025-09-16',
    content: '<p>This comprehensive guide walks you through setting up a Next.js project with Tailwind CSS, covering installation, configuration, and best practices for creating responsive, high-performance websites. Learn how to leverage Next.js App Router and Tailwind\'s utility-first approach to streamline development. (Add 500+ words of detailed steps, code snippets, and tips for optimization here...)</p>',
  },
  {
    slug: 'adsense-tips',
    title: 'Tips for AdSense Approval in 2025',
    excerpt: 'How to get your blog monetized quickly.',
    date: '2025-09-16',
    content: '<p>Monetizing your blog with Google AdSense requires careful planning. This post covers essential steps like creating high-quality content, ensuring a user-friendly design, and meeting AdSense policies. Discover strategies to boost your approval chances, including niche selection and SEO optimization. (Add 500+ words of actionable advice, policy breakdowns, and examples here...)</p>',
  },
  {
    slug: 'react-hooks-guide',
    title: 'Mastering React Hooks for Beginners',
    excerpt: 'Learn how to use React Hooks to manage state and side effects.',
    date: '2025-09-15',
    content: '<p>React Hooks revolutionized functional components by enabling state and lifecycle management without classes. This tutorial explains useState, useEffect, and custom hooks with practical examples. Build a simple counter app and understand best practices for clean code. (Add 500+ words of code examples, use cases, and performance tips here...)</p>',
  },
  {
    slug: 'seo-for-nextjs',
    title: 'SEO Best Practices for Next.js Websites',
    excerpt: 'Optimize your Next.js site for search engines with these techniques.',
    date: '2025-09-14',
    content: '<p>Search engine optimization is critical for driving traffic. This post covers Next.js-specific SEO strategies, including dynamic meta tags, sitemaps, and server-side rendering. Learn how to use Vercel analytics and Google Search Console effectively. (Add 500+ words of detailed SEO techniques, tools, and case studies here...)</p>',
  },
  {
    slug: 'tailwind-responsive-design',
    title: 'Building Responsive Designs with Tailwind CSS',
    excerpt: 'Create mobile-first layouts with Tailwind’s utility classes.',
    date: '2025-09-13',
    content: '<p>Tailwind CSS simplifies responsive design with its utility-first approach. This guide walks you through creating a responsive blog layout, covering breakpoints, flexbox, and grid systems. Includes tips for accessibility and performance. (Add 500+ words of step-by-step instructions, code snippets, and design patterns here...)</p>',
  },
  {
    slug: 'nextjs-api-routes',
    title: 'Using API Routes in Next.js for Backend Logic',
    excerpt: 'Learn how to build serverless APIs with Next.js.',
    date: '2025-09-12',
    content: '<p>Next.js API routes allow you to create backend endpoints within your frontend app. This tutorial demonstrates how to set up a simple CRUD API for a blog, handling GET and POST requests. Includes security best practices. (Add 500+ words of code examples, database integration, and deployment tips here...)</p>',
  },
  {
    slug: 'javascript-promises',
    title: 'Understanding JavaScript Promises and Async/Await',
    excerpt: 'Master asynchronous JavaScript with real-world examples.',
    date: '2025-09-11',
    content: '<p>JavaScript’s asynchronous nature can be tricky. This post explains Promises and async/await syntax through practical examples like fetching data from an API. Learn error handling and performance optimization techniques. (Add 500+ words of detailed explanations, code snippets, and use cases here...)</p>',
  },
  {
    slug: 'deploy-nextjs-vercel',
    title: 'Deploying Next.js Apps to Vercel',
    excerpt: 'Step-by-step guide to deploying your Next.js app.',
    date: '2025-09-10',
    content: '<p>Vercel is the go-to platform for Next.js deployment. This tutorial covers setting up a project, configuring domains, and enabling automatic scaling. Includes tips for environment variables and preview deployments. (Add 500+ words of deployment steps, CI/CD setup, and troubleshooting here...)</p>',
  },
  {
    slug: 'css-grid-vs-flexbox',
    title: 'CSS Grid vs. Flexbox: When to Use Which',
    excerpt: 'Understand the differences between CSS Grid and Flexbox.',
    date: '2025-09-09',
    content: '<p>CSS Grid and Flexbox are powerful layout tools. This post compares their strengths, with examples like building a dashboard layout. Learn when to choose Grid for two-dimensional layouts or Flexbox for one-dimensional ones. (Add 500+ words of comparisons, code demos, and practical tips here...)</p>',
  },
  {
    slug: 'typescript-nextjs',
    title: 'Why Use TypeScript with Next.js',
    excerpt: 'Boost your Next.js app with TypeScript’s type safety.',
    date: '2025-09-08',
    content: '<p>TypeScript enhances Next.js development by catching errors early. This guide shows how to set up TypeScript, type props, and integrate with APIs. Includes a sample typed blog component. (Add 500+ words of setup steps, typing examples, and benefits here...)</p>',
  },
  {
    slug: 'web-performance-optimization',
    title: 'Optimizing Web Performance in 2025',
    excerpt: 'Techniques to make your website load faster.',
    date: '2025-09-07',
    content: '<p>Fast websites improve user experience and SEO. This post covers image optimization, lazy loading, and code splitting in Next.js. Learn how to use Lighthouse to measure and improve performance. (Add 500+ words of optimization techniques, tools, and metrics here...)</p>',
  },
  {
    slug: 'accessible-web-design',
    title: 'Building Accessible Websites with WCAG Guidelines',
    excerpt: 'Ensure your site is usable for everyone.',
    date: '2025-09-06',
    content: '<p>Accessibility is a must for modern websites. This tutorial explains WCAG guidelines, with practical steps for adding ARIA labels, keyboard navigation, and screen reader support in Next.js. (Add 500+ words of accessibility tips, tools, and testing methods here...)</p>',
  },
];