export default function Head() {
  return (
    <>
      <title>PanKri</title>
      <meta name="description" content="Generated by PanKri" />
      <meta
        name="google-site-verification"
        content="0i_AL_KPpPk8XPU1FL6OBnbemfbvSW1VAAemBI5e6lw"
      />
    </>
  );
}
