import Navbar from "@/components/Navbar";
import Head from "next/head";
import "./globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>PanKri</title>
        <meta name="description" content="Generated by PanKri" />
        <meta
          name="google-site-verification"
          content="0i_AL_KPpPk8XPU1FL6OBnbemfbvSW1VAAemBI5e6lw"
        />
      </Head>
      <body className="mx-3 md:mx-16 lg:mx-32 my-2">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
