import Navbar from "@/components/Navbar";
import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "PanKri",
  description: "Generated by PanKri",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-3 md:mx-16 lg:mx-32 my-2">
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2178056161997357"
          crossorigin="anonymous"
        ></Script>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
